version: '3.8'

services:

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "80:80"

    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "5000:5000"

    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
