pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/yashwanth13113/Aws_Devops_Handson.git'
            }
        }

        stage('Stop Old Containers') {
            steps {
                dir('devops-project') {
                    sh 'docker compose down || true'
                }
            }
        }

        stage('Build') {
            steps {
                dir('devops-project') {
                    sh 'docker compose build'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('devops-project') {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Verify') {
            steps {
                sh 'docker ps'
            }
        }
    }
}
